apiVersion: v1
kind: Service
metadata:
  name: sample-nginx
spec:
  type: LoadBalancer
  selector:
    app: sample-nginx
  ports:
    - name: http
      port: 8080
      targetPort: 80 ##nginx-deployment.yamlのcontainerPortと同値
