apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:     #リクエストをラベルと一致するポッドへ送る。
    app: web    #app: webにリクエストが送られる。
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
